version: '3.7'
networks:
  web-release:
    driver: bridge
services:
  db_postgres:
    image: postgres
    volumes:
      - ./db:/var/lib/postgres/data/
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    networks:
      - web-release
  mvc-proj:
    image: mvc
    build:
      context: .
      dockerfile: asp/Dockerfile
    ports:
      - 5199:8080
    networks:
        - web-release